'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'it' | 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Prodotti',
    'nav.company': "L'Azienda",
    'nav.events': 'Eventi',
    'nav.contacts': 'Contatti',
    
    // Home
    'home.hero.title': 'Flli Pozzi srl',
    'home.hero.subtitle': 'Dal 1947, leader nell\'imballaggio',
    'home.features.madeInItaly': 'Made in Italy',
    'home.features.madeInItaly.desc': 'Qualità italiana riconosciuta in tutto il mondo',
    'home.features.excellence': 'Eccellenza',
    'home.features.excellence.desc': 'Prodotti di alta qualità per ogni esigenza',
    'home.features.assistance': 'Assistenza',
    'home.features.assistance.desc': 'Supporto tecnico qualificato e formazione',
    'home.reggiatrici.title': 'Reggiatrici dal 1947',
    'home.reggiatrici.text': 'Produciamo reggiatrici e tenditori manuali Made in Italy, sinonimo di qualità, resistenza e affidabilità. Adatto a diverse applicazioni industriali, ogni apparecchio è stato progettato per rendere al meglio sotto ogni sforzo. Con Noi, otterrete non solo tendireggia di qualità superiore, ma anche la certezza di investire in soluzioni di imballaggio progettate per durare nel tempo e affrontare sfide industriali con successo.',
    'home.reggiatrici.button': 'Tutte le reggiatrici',
    'home.assistance.title': 'Assistenza tecnica e formazione',
    'home.assistance.rapid': 'Interventi rapidi',
    'home.assistance.rapid.desc': 'Garantiamo interventi rapidi di assistenza e manutenzione programmata su tutte le macchine e i prodotti commercializzati.',
    'home.assistance.spare': 'Ricambi originali',
    'home.assistance.spare.desc': 'Forniamo ricambi originali per mantenere le prestazioni ottimali nel tempo, anche in ambienti di lavoro ad alta intensità.',
    'home.assistance.docs': 'Documentazione e formazione',
    'home.assistance.docs.desc': 'I nostri tecnici consegnano la documentazione tecnica completa (manuali, lista ricambi, certificazioni) e offrono formazione dedicata al personale addetto alla manutenzione, nel pieno rispetto delle normative vigenti.',
    'home.solutions.title': 'Soluzioni personalizzate per ogni esigenza',
    'home.solutions.text': 'Presso la F.lli Pozzi, potete scegliere tra la nostra gamma di tendireggia manuali, e soluzioni innovative e affidabili per soddisfare le esigenze di imballaggio di aziende di ogni dimensione e settore. La nostra esperienza nel settore ci consente di comprendere appieno le sfide dell\'imballaggio industriale e di fornire consulenza personalizzata per garantire la scelta dei prodotti più adatti alle vostre esigenze.',
    'home.solutions.button': 'Forniture per l\'imballaggio',
    'home.cta.title': 'Scegliete l\'eccellenza nell\'imballaggio',
    'home.cta.text': 'Scegliendoci, scegliete l\'eccellenza nell\'imballaggio. Contattateci oggi per scoprire come possiamo contribuire a ottimizzare il vostro processo di imballaggio e migliorare la vostra efficienza operativa.',
    'home.cta.button': 'Contattaci',
    'home.reggia.title': 'Reggia',
    'home.reggia.desc': 'Reggia in polipropilene, poliestere e acciaio, per ogni esigenza di imballaggio industriale.',
    'home.reggia.button': 'Vedi prodotti',
    'home.sigilli.title': 'Sigilli',
    'home.sigilli.desc': 'Sigilli per reggia in polipropilene, poliestere e acciaio, con diverse finiture.',
    'home.sigilli.button': 'Vedi prodotti',
    
    // Azienda
    'azienda.paragraph1': 'La ditta Fratelli Pozzi nasce nel 1947 nel territorio Bergamasco con dimensioni artigiane: da allora ha registrato una continua crescita sia in termini di gamma di prodotti, che di capacità produttiva, trasformando una piccola attività territoriale in una vera e propria realtà aziendale sviluppando una rete commerciale diffusa in gran parte del mondo.',
    'azienda.paragraph2': 'L\'Azienda da oltre 70 anni, Leader nel proprio settore, si distingue per l\'elevata qualità dei propri prodotti, riconosciuti in tutto il mondo per il proprio "Made in Italy", e per la qualificata assistenza che è in grado di fornire alla propria clientela.',
    'azienda.paragraph3': 'La ditta dispone di un moderno capannone con una superficie di 2200 mq., all\'interno del quale viene effettuata la produzione, l\'assemblaggio dei tendireggia, lo stoccaggio di tutti i materiali di consumo e l\'assistenza tecnica per ogni tipo di reggiatrice.',
    'azienda.values.title': 'I nostri valori',
    'azienda.values.madeInItaly': 'Made in Italy',
    'azienda.values.madeInItaly.desc': 'Qualità italiana riconosciuta a livello internazionale, frutto di oltre 75 anni di esperienza e innovazione.',
    'azienda.values.excellence': 'Eccellenza',
    'azienda.values.excellence.desc': 'Prodotti di alta qualità progettati per durare nel tempo e soddisfare le esigenze più esigenti del mercato.',
    'azienda.values.assistance': 'Assistenza',
    'azienda.values.assistance.desc': 'Supporto tecnico qualificato, formazione del personale e fornitura di pezzi di ricambio originali.',
    'azienda.cta.text': 'Contattateci oggi per scoprire come possiamo contribuire a ottimizzare il vostro processo di imballaggio e migliorare la vostra efficienza operativa.',
    'azienda.cta.button': 'Contattaci',
    
    // Contatti
    'contatti.title': 'Informazioni di contatto',
    'contatti.address': 'Indirizzo:',
    'contatti.address.value': 'Via Leonardo da Vinci 37, Caravaggio 24043 (BG), Italy',
    'contatti.phone': 'Telefono:',
    'contatti.email': 'E-mail:',
    'contatti.form.title': 'Invia un messaggio',
    'contatti.form.name': 'Nome',
    'contatti.form.email': 'Email',
    'contatti.form.phone': 'Telefono',
    'contatti.form.phone.required': 'Telefono *',
    'contatti.form.message': 'Messaggio',
    'contatti.form.submit': 'Invia',
    'contatti.form.submitting': 'Invio in corso...',
    'contatti.form.success': 'Grazie per il tuo messaggio! Ti contatteremo presto.',
    'contatti.form.error.name': 'Il nome deve contenere almeno 2 caratteri',
    'contatti.form.error.email': 'Email non valida',
    'contatti.form.error.phone': 'Il telefono è obbligatorio',
    'contatti.form.error.message': 'Il messaggio deve contenere almeno 10 caratteri',
    'contatti.form.error.submit': 'Si è verificato un errore durante l\'invio. Riprova più tardi.',
    'contatti.cta.text': 'Contattateci oggi per qualsiasi informazione o preventivo. Siamo qui per aiutarvi a trovare la soluzione di imballaggio perfetta per le vostre esigenze.',
    'contatti.cta.button': 'Contattaci',
    
    // Eventi
    'eventi.title': 'Eventi e Fiere',
    'eventi.description': 'Scopri gli eventi e le fiere a cui partecipa Flli Pozzi nel settore dell\'imballaggio industriale.',
    'eventi.ipack2025.title': 'IPACK-IMA 2025',
    'eventi.ipack2025.text1': 'F.lli Pozzi sarà presente a Ipack-Ima 2025, la principale fiera internazionale dedicata alle tecnologie per il packaging e l\'industria di processo.',
    'eventi.ipack2025.text2': 'Durante l\'evento presenteremo in anteprima il nostro nuovo brevetto. Una soluzione innovativa pensata per migliorare efficienza, ergonomia e prestazioni.',
    'eventi.ipack2025.text3': 'Gli obiettivi sono consolidare le relazioni commerciali in essere ed entrare in contatto con nuovi operatori.',
    'eventi.ipack2025.moreInfo': 'Maggiori info cliccando sul banner.',
    'eventi.ipack2022.title': 'IPACK-IMA 2022',
    'eventi.ipack2022.text1': 'Fratelli Pozzi ha partecipato a Ipack-Ima 2022, appuntamento principale nel processing e packaging per i professionisti dei settori food e non food, nonché piattaforma internazionale per il rilancio delle attività.',
    'eventi.ipack2022.text2': 'Le finalità conseguite sono promuovere a livello globale l\'immagine aziendale, presentare i nuovi prodotti, instaurare e consolidare le relazioni commerciali a livello internazionale.',
    'eventi.ipack2022.text3': 'I risultati principali in fase di raggiungimento sono incremento della clientela e del fatturato.',
    'eventi.months.gennaio': 'GENNAIO',
    'eventi.months.febbraio': 'FEBBRAIO',
    'eventi.months.marzo': 'MARZO',
    'eventi.months.aprile': 'APRILE',
    'eventi.months.maggio': 'MAGGIO',
    'eventi.months.giugno': 'GIUGNO',
    'eventi.months.luglio': 'LUGLIO',
    'eventi.months.agosto': 'AGOSTO',
    'eventi.months.settembre': 'SETTEMBRE',
    'eventi.months.ottobre': 'OTTOBRE',
    'eventi.months.novembre': 'NOVEMBRE',
    'eventi.months.dicembre': 'DICEMBRE',
    
    // Prodotti
    'prodotti.categories.reggiatrici': 'Reggiatrici e tendireggia',
    'prodotti.categories.reggiatrici.desc': 'Manuali, a batteria e pneumatiche',
    'prodotti.categories.carrelli': 'Carrelli',
    'prodotti.categories.carrelli.desc': 'Porta reggia',
    'prodotti.categories.reggia': 'Reggia',
    'prodotti.categories.reggia.desc': 'Poliestere, polipropilene e acciaio',
    'prodotti.categories.sigilli': 'Sigilli',
    'prodotti.categories.sigilli.desc': 'Lucidi o zincati',
    'prodotti.categories.accessori': 'Accessori per il packaging',
    'prodotti.categories.accessori.desc': 'Forniture per l\'imballaggio',
    'prodotti.quickNav.title': 'Navigazione rapida',
    'prodotti.cta.text': 'Accanto alla nostra produzione, offriamo anche una gamma di prodotti complementari per l\'imballaggio, selezionati per qualità e affidabilità. Contattaci per scoprire tutte le soluzioni disponibili.',
    'prodotti.cta.button': 'Richiedi informazioni',
    'prodotti.description.plastica': 'Prodotti in acciaio lucido o zincato, con superficie liscia o bulinata. A richiesta con marchio del cliente.',
    'prodotti.sections.reggiatrici.manuali': 'Tendireggia manuali per reggia polipropilene e poliestere',
    'prodotti.sections.reggiatrici.batteria': 'Reggiatrici a batteria per reggia in polipropilene e poliestere',
    'prodotti.sections.reggiatrici.pneumaticheVibrazione': 'Reggiatrici pneumatiche a vibrazione per reggia in polipropilene e poliestere',
    'prodotti.sections.reggiatrici.pneumaticheAcciaioConSigillo': 'Reggiatrici pneumatiche per reggia acciaio con sigillo colli piani e tondi',
    'prodotti.sections.reggiatrici.pneumaticheAcciaioSenzaSigillo': 'Reggiatrici pneumatiche per reggia acciaio senza sigillo colli piani',
    'prodotti.sections.carrelli': 'Carrelli porta reggia',
    'prodotti.sections.reggia.title': 'Reggia',
    'prodotti.sections.reggia.polipropilene': 'Reggia in polipropilene 100% Riciclabile',
    'prodotti.sections.reggia.poliestere': 'Reggia in poliestere',
    'prodotti.sections.reggia.acciaio': 'Reggia in acciaio',
    'prodotti.sections.reggia.acciaio.desc': 'Monospira o matassata, è disponibile lucida, zincata, bluata o verniciata.',
    'prodotti.sections.reggia.onRequest': 'A richiesta è disponibile colore e marchio del cliente.',
    'prodotti.sections.sigilli.plastica': 'Sigilli per reggia in plastica (PP) e poliestere (PET) (tendireggia manuali)',
    'prodotti.sections.sigilli.acciaio': 'Sigilli per reggia in acciaio',
    'prodotti.sections.sigilli.bulinatiLucidi': 'Bulinati lucidi',
    'prodotti.sections.sigilli.bulinatiZincati': 'Bulinati zincati',
    'prodotti.sections.sigilli.zincati': 'Zincati',
    'prodotti.sections.sigilli.overlap': 'Overlap',
    'prodotti.table.section': 'Sezione in mm',
    'prodotti.table.measure': 'Misura in mm',
    'prodotti.table.resistance': 'Resistenza in kg',
    'prodotti.table.length': 'Lunghezza in metri',
    'prodotti.table.article': 'Articolo',
    'prodotti.table.dimensions': 'Dim. mm',
    'prodotti.table.quantity': 'Qtà',
    'prodotti.table.model': 'Modello',
    'prodotti.table.tensileStrength': 'Resistenza alla trazione',
    'prodotti.table.quantityFull': 'Quantità',
    'prodotti.steel.polished': 'Lucida',
    'prodotti.steel.galvanized': 'Zincata',
    'prodotti.steel.blued': 'Bluata',
    'prodotti.steel.painted': 'Verniciata',
    'prodotti.steel.highResistance': 'Alta resistenza',
    'prodotti.steel.upTo': 'fino a',
    // Descrizioni prodotti - Reggiatrici manuali
    'prodotti.descriptions.CP2000': 'Tendireggia manuale per reggia in polipropilene da mm 9 a 19 con sigillo serie A.',
    'prodotti.descriptions.BEST': 'Tendireggia manuale per reggia in polipropilene da mm 9 a 19 con tensionamento speciale, per sigillo serie A.',
    'prodotti.descriptions.PLRG': 'Tendireggia manuale per reggia in polipropilene da mm 9 a 19 con tensionamento veloce, per sigillo serie A.',
    // Descrizioni prodotti - Reggiatrici a batteria
    'prodotti.descriptions.GTSMART': 'Reggiatrice a batteria per reggia tipo PP/PET mm 13/16 saldatura a vibrazione colli piani e tondi . Tensione regolabile fino a 3000 N. Per spessori della reggia fino a mm 1,0. La batteria 14V / 3.0 AH LI-ION si ricarica in soli 15 minuti.',
    'prodotti.descriptions.GTONE': 'Reggiatrice a batteria per reggia in PP/PET mm 13/16/19 saldatura a vibrazione colli piani e tondi. Tensione regolabile fino a 3000 N. Per spessori della reggia da 0,8 a 1,2. La batteria 14V / 3.0 AH LI-ION si ricarica in soli 15 minuti.',
    'prodotti.descriptions.GTXTREME': 'Reggiatrice a batteria per reggia tipo PET mm 19/25 saldatura a vibrazione colli piani e tondi . Tensione regolabile fino a 5000 N. Per spessori della reggia fino a mm 1,3. La batteria 14V / 3.0 AH LI-ION si ricarica in soli 15 minuti.',
    'prodotti.descriptions.CP007': 'Reggiatrice a batteria per reggia tipo PP/PET mm 13/16 con tensionamento manuale e saldatura a vibrazione, colli piani e tondi. Tensione regolabile fino a 2000 N. Per spessori della reggia fino a mm 1,0. La batteria 14V / 3.0 AH LI-ION si ricarica in soli 15 minuti.',
    'prodotti.descriptions.GTMAX': 'Reggiatrice a batteria per reggia tipo PET mm 19/25 saldatura a vibrazione colli piani e tondi. Tensione regolabile fino a 5000 N. Per spessori della reggia fino a mm 1,3. La batteria 14V / 3.0 AH LI-ION si ricarica in soli 15 minuti.',
    'prodotti.descriptions.VIPER': 'Reggiatrice a batteria per reggia tipo PET mm 9/12/16/19 saldatura a vibrazione colli piani e tondi . La forza di tensionamento è programmabile in Newton, Kg e libbre. Costituita da un\'innovativa interfaccia touchscreen. Batteria da 18V / 3.0 AH LI-ION.',
    // Descrizioni prodotti - Reggiatrici pneumatiche vibrazione
    'prodotti.descriptions.FASTPNLT': 'Reggiatrice pneumatica per reggia in PP/PET mm 13/16/19 saldatura a vibrazione colli piani e tondi tensione regolabile fino a 2000 N – per spessori della reggia fino a mm 1.',
    'prodotti.descriptions.FASTPNHIGHTENSION': 'Reggiatrice pneumatica per reggia in Poliestere mm 19/25/32 saldatura a vibrazione colli piani e tondi tensione regolabile fino a 6000 N – per spessori della reggia fino a mm 1,3.',
    // Descrizioni prodotti - Reggiatrici pneumatiche acciaio con sigillo
    'prodotti.descriptions.FP131619': 'Reggiatrice pneumatica per reggia in acciaio da mm 13, 16 e 19, con sigillo serie F (Overlap). Ottima per la reggiatura di colli tondi. Spessore da 0,5 a 0,6 mm. Peso: 4,5 kg.',
    'prodotti.descriptions.FP19S25S32S': 'Reggiatrice pneumatica per reggia in acciaio da mm 19, 25 e 32, con sigillo serie F (Overlap). Pesa solo Kg. 10 ed ideale per la reggiatura di colli piani e tondi, spessore da 0,8 a 0,9 mm.',
    'prodotti.descriptions.FP32PLUS': 'Reggiatrice pneumatica per reggia in acciaio da mm 19, 25 e 32, con sigillo serie F (Overlap). Spessore da 1,0 a 1,2 mm.',
    // Descrizioni prodotti - Reggiatrici pneumatiche acciaio senza sigillo
    'prodotti.descriptions.SL3PN': 'Reggiatrice pneumatica senza sigillo per reggia in acciaio da mm 13, 16 e 19. Spessore max mm 0,6. Peso: 7 Kg.',
    // Descrizioni prodotti - Carrelli
    'prodotti.descriptions.GM15': 'Carrello porta reggia per bobine in polipropilene mm 9 -19, completo di cassetta per contenere tendireggia e sigilli. Diametro interno da mm 390 o 405.',
    'prodotti.descriptions.FP15': 'Carrello porta reggia per bobine in polipropilene mm 9 -19, completo di cassetta per contenere tendireggia e sigilli. Diametro interno da mm 150/200/280/405.',
    'prodotti.descriptions.FP93': 'Carrello porta reggia per bobine in poliestere e acciaio da mm 9-32 e diametro interno 405 e acciaio con matassata mm 13-19 e diametro interno 405, completo di cassetta per contenere tendireggia e sigilli. Diametro interno da mm 390 o 405.',
    'prodotti.descriptions.FP15S': 'Carrello porta reggia per bobine in polipropilene con diametro interno mm 200-280. Completo di freno e cassetta per contenere tendireggia e sigilli.',
    'prodotti.descriptions.FP92': 'Carrello porta reggia per bobine in acciaio in rotoli monospira da 13 a 32 mm, completo di cassetta per contenere tendireggia e sigilli.',
    'prodotti.descriptions.FP13': 'Carrello porta reggia per bobine tessili in poliestere con diam. int. mm 76 larghezza mm. 140 e 150.',
    
    // Footer
    'footer.tagline': 'Dal 1947, leader nell\'imballaggio',
    'footer.links.title': 'Link',
    'footer.info.title': 'Informazioni',
    'footer.contacts.title': 'Contatti',
    'footer.contacts.address': 'Indirizzo: Via L. Da Vinci 37, Caravaggio (BG), Italy',
    'footer.contacts.phone': 'Telefono:',
    'footer.contacts.email': 'E-mail:',
    'footer.privacy': 'Privacy Policy',
    'footer.cookies': 'Cookie Policy',
    'footer.quality': 'Qualità',
    'footer.certification': 'Certificazione',
    'footer.copyright': 'Copyright © 2026 Flli Pozzi srl | All Rights Reserved. P.IVA 00215550161',
    
    // Cookies
    'cookies.title': 'Cookie Policy',
    'cookies.subtitle': 'Informazioni sui cookie',
    'cookies.intro': 'Fratelli Pozzi S.r.l. fornisce di seguito le informazioni relative al funzionamento dei cookie all\'interno del sito (in seguito "Sito"), anche ai sensi del Provvedimento del Garante della Privacy "Individuazione delle modalità semplificate per l\'informativa e l\'acquisizione del consenso per l\'uso dei cookie" di data 8 maggio 2014 (in seguito "Provvedimento").',
    'cookies.whatAre': 'I cookie sono stringhe di testo che identificano il computer (attraverso il cosiddetto indirizzo IP) sul nostro server, permettendo di memorizzare informazioni da riutilizzare nel corso della medesima, o successiva, visita al sito. Per informazioni sui motivi per cui li usiamo fare riferimento alla sezione "Come utilizziamo le informazioni raccolte" della presente Privacy Policy. Non usiamo l\'indirizzo IP come mezzo per identificare l\'utente.',
    'cookies.storage': 'I cookie vengono memorizzati in base alle preferenze dell\'Utente, dal singolo browser, sullo specifico dispositivo. In genere, c\'è la possibilità di impostare il computer in modo che: accetti tutti i cookie, essere informato quando viene emesso un cookie o per non ricevere i cookie.',
    'cookies.browserSettings': 'Con la maggior parte dei browser, questa funzione può essere raggiunta tramite il menu "tools" (ad es. Internet Explorer), "edit" o "task" (ad es. Netscape). In caso di difficoltà a trovare quest\'area, la funzione "aiuto" all\'interno del browser sarà in grado di fornire assistenza. Si possono, inoltre, trovare informazioni più dettagliate sui cookie e su come gestirli su',
    'cookies.necessary': 'Questi cookie sono strettamente necessari per fornirLe i servizi disponibili attraverso il nostro sito Web e per utilizzare alcune delle sue funzionalità.',
    'cookies.disabling': 'È importante notare che disabilitando tutti i Cookie, il funzionamento di questo sito potrebbe essere compromesso.',
    'cookies.thirdParty': 'In caso di servizi erogati da terze parti, l\'Utente può inoltre esercitare il proprio diritto a opporsi al tracciamento informandosi tramite la privacy policy della terza parte, tramite il link di opt-out, se esplicitamente fornito, o contattando direttamente la stessa.',
    'cookies.howUse': 'Come utilizziamo i cookie?',
    'cookies.howUse.text1': 'In base alla funzione e alla finalità di utilizzo i cookie possono essere classificati in cookie tecnici, cookie analitici, cookie di profilazione. Tutti i cookie si distinguono in cookie di prima parte, installati direttamente dal gestore del Sito e in cookie di terze parti, installati attraverso il Sito da soggetti terzi.',
    'cookies.howUse.text2': 'In base alle caratteristiche e all\'utilizzo dei cookie possiamo distinguere diverse categorie:',
    'cookies.navigation.title': 'Cookie di Navigazione',
    'cookies.navigation.text1': 'Tramite i Cookie di Navigazione il Sito traccia il percorso del cookie (cosiddetta attività di "click stream" ovverosia di registrazione dei percorsi seguiti dai visitatori di un sito nel passaggio da una pagina all\'altra) senza che da questa attività possa comunque conoscere o identificare l\'utente che è entrato nel sito, al fine di raccogliere dati statistici sul sito quali, ad esempio, le pagine visitate, le pagine scaricate ecc.',
    'cookies.navigation.text2': 'Ribadiamo che nessuna di queste informazioni è associata a Lei in maniera individuale. I cookie non catturano il vostro indirizzo e-mail personale, né alcuna vostra informazione privata. Le informazioni ricavate dal tracciamento dei cookie vengono valutate solo complessivamente. Vengono utilizzati altresì, i file di log del server Web per contare i visitatori e valutare le capacità tecniche del nostro sito. Ci serviamo di tutte queste informazioni per sapere quante persone visitano il Sito, per organizzare le pagine nella maniera più accessibile possibile, per facilitare la navigazione sul sito e per rendere le sue pagine più utili per gli utenti. Raccogliamo informazioni sul traffico del sito, ma non sui singoli visitatori. Di conseguenza, nessuna informazione che La riguardi in particolare potrà essere conservata o utilizzata.',
    'cookies.session.title': 'Cookie di Sessione',
    'cookies.session.text1': 'I Cookie di Sessione sono strettamente necessari per fornirLe i servizi disponibili attraverso il nostro sito Web e per utilizzare alcune delle sue funzionalità.',
    'cookies.session.text2': 'Poiché questi cookie sono strettamente necessari per fornire il sito Web, non è possibile rifiutarli senza influire sul funzionamento del nostro sito, ma è comunque possibile bloccarli o eliminarli modificando le impostazioni del browser e imporre il blocco di tutti i cookie su questo sito Web.',
    'cookies.analytics.title': 'Google Analytics Cookie',
    'cookies.analytics.text1': 'I Google Analytics Cookie raccolgono informazioni che vengono utilizzate in forma aggregata per aiutarci a capire come viene utilizzato il nostro sito web o l\'efficacia delle nostre campagne di marketing o per aiutarci a personalizzare il sito al fine di migliorare la Sua esperienza.',
    'cookies.analytics.text2': 'Questo sito web utilizza Google Analytics, un servizio di analisi web fornito da Google, Inc. ("Google"). Google Analytics utilizza dei "cookies" che sono file di testo depositati sul vostro computer per consentire al sito web di analizzare come gli utenti utilizzano il sito. Le informazioni generate dal cookie sull\'utilizzo del sito web (compreso il Vostro indirizzo IP anonimo) verranno trasmesse e depositate presso i server di Google negli Stati Uniti.',
    'cookies.analytics.text3': 'Google utilizzerà queste informazioni allo scopo di esaminare il Vostro utilizzo del sito web, compilare report sulle attività del sito per gli operatori dello stesso e fornire altri servizi relativi alle attività del sito web e all\'utilizzo di internet. Google può anche trasferire queste informazioni a terzi ove ciò sia imposto dalla legge o laddove tali terzi trattino le suddette informazioni per conto di Google. Google non assocerà il vostro indirizzo IP a nessun altro dato posseduto da Google.',
    'cookies.analytics.text4': 'Potete rifiutarvi di usare i cookies selezionando l\'impostazione appropriata sul vostro browser ma si prega di notare che se si fa questo non si può essere in grado di utilizzare tutte le funzionalità di questo sito web.',
    'cookies.analytics.text5': 'Si può impedire a Google il rilevamento di un cookie che viene generato a causa di e legato al Vostro utilizzo di questo sito web (compreso il Vostro indirizzo IP) e l\'elaborazione di tali dati scaricando ed installando questo plugin per il browser:',
    'cookies.analytics.text6': 'La privacy policy utilizzata da Google per la funzionalità Analytics è consultabile a questo link:',
    'cookies.profiling.title': 'Cookie di Profilazione',
    'cookies.profiling.text1': 'I Cookie di Profilazione creano profili relativi all\'utente e vengono utilizzati al fine di inviare messaggi pubblicitari in linea con le preferenze manifestate dallo stesso nell\'ambito della navigazione in rete.',
    'cookies.profiling.text2': 'Il titolare ha deciso di non utilizzarli in ragione della particolare invasività che tali dispositivi possono avere nell\'ambito della sfera privata degli utenti.',
    'cookies.sharing.text1': 'I cookie raccolti per le finalità elencate in precedenza potranno essere comunicati ai soggetti competenti incaricati della gestione del sito per lo svolgimento, anche parziale, di attività inerenti l\'incarico.',
    'cookies.sharing.text2': 'Il presente Sito fa esclusivamente uso di cookie tecnici, di navigazione o sessione e analytics, per consentire la navigazione e fornire il servizio richiesto dall\'Utente.',
    'cookies.sharing.text3': 'Per tutti i cookie diversi da quelli tecnici è richiesto il consenso espresso dell\'Utente la prima volta che visita il Sito. Viene tenuta traccia del consenso in occasione delle visite successive, tuttavia l\'Utente ha sempre la possibilità di revocare in tutto o in parte il consenso già espresso.',
    'cookies.duration.title': 'Durata',
    'cookies.duration.text1': 'Alcuni cookie (cookie di sessione) restano attivi solo fino alla chiusura del browser. Altri cookie (cookie persistenti) "sopravvivono" alla chiusura del browser e sono disponibili anche in successive visite dell\'utente, e la loro durata è fissata dal server al momento della loro creazione con una data di scadenza prestabilita.',
    'cookies.duration.text2': 'L\'impostazione può essere definita in modo specifico per i diversi siti e applicazioni web. Inoltre i più comuni browser consentono di definire impostazioni diverse per vari tipi di cookie.',
    'cookies.duration.text3': 'Può impostare il browser per essere avvisato in caso di tentativi di inserimento dei cookie, limitarli o rifiutarli completamente.',
    'cookies.changes.title': 'Modifiche alla presente informativa',
    'cookies.changes.text': 'La presente Informativa è in vigore dal 25 maggio 2018. Fratelli Pozzi S.r.l. si riserva di modificarne il contenuto, in parte o completamente, anche a causa di variazioni della Normativa Privacy. Fratelli Pozzi S.r.l. effettuerà la Pubblicazione sul Sito della versione aggiornata del presente atto, e da quel momento essa sarà vincolante: pertanto si invita a visitare con regolarità questa sezione.',
    'cookies.dataController': 'Titolare del trattamento dati:',
    'cookies.dataController.value': 'Fratelli Pozzi S.r.l. con sede in via Leonardo Da Vinci, 37 Caravaggio, 24043 BG – P.IVA 00215550161.',
    'cookies.moreInfo': 'Vista l\'oggettiva complessità legata all\'identificazione delle tecnologie basate sui Cookie e alla loro integrazione molto stretta con il funzionamento del web, si rimanda al seguente link',
    
    // Privacy
    'privacy.title': 'Informativa Privacy',
    'privacy.subtitle': 'Gestione dei dati personali',
    'privacy.intro1': 'Fratelli Pozzi S.r.l. ai sensi del Decreto Legislativo 30 Giugno 2003, n. 196 – Codice della privacy (di seguito "Codice") modificato e aggiornato dal D.Lgs. 101/2018, degli articoli 4, n. 7), 13, 14 e 24 del Regolamento UE n. 679 del 27 aprile 2016 relativo alla protezione delle persone fisiche con riguardo al trattamento dei dati personali, nonché alla libera circolazione di tali dati (di seguito, "Regolamento" o "GDPR"), La informa che nello svolgimento della propria attività pone la massima attenzione alla sicurezza e alla riservatezza dei dati personali dei propri utenti.',
    'privacy.intro2': 'La Società è pertanto titolare del trattamento dei dati personali raccolti sul presente sito web. Il Regolamento è nato con l\'intento di uniformare la normativa dell\'Unione europea, garantendo un maggiore controllo su come vengono trattati i dati personali. A seguito dell\'entrata in vigore, avvenuta in data 25 maggio 2018, la Società ha intrapreso un percorso di adeguamento dei processi e delle politiche interne nella protezione di tutte le informazioni di cui la nostra Società entrerà in possesso. Questa dichiarazione descrive quali tipi di informazioni raccogliamo, come vengono utilizzate, cosa condividiamo con altre organizzazioni, come possono essere esercitati i diritti riguardo alle informazioni in nostro possesso e come contattare la nostra realtà.',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.company': 'Company',
    'nav.events': 'Events',
    'nav.contacts': 'Contacts',
    
    // Home
    'home.hero.title': 'Flli Pozzi srl',
    'home.hero.subtitle': 'Since 1947, leader in packaging',
    'home.features.madeInItaly': 'Made in Italy',
    'home.features.madeInItaly.desc': 'Italian quality recognized worldwide',
    'home.features.excellence': 'Excellence',
    'home.features.excellence.desc': 'High quality products for every need',
    'home.features.assistance': 'Assistance',
    'home.features.assistance.desc': 'Qualified technical support and training',
    'home.reggiatrici.title': 'Strapping machines since 1947',
    'home.reggiatrici.text': 'We produce manual strapping machines and tensioners Made in Italy, synonymous with quality, resistance and reliability. Suitable for various industrial applications, each device has been designed to perform at its best under every effort. With Us, you will get not only superior quality strapping, but also the certainty of investing in packaging solutions designed to last over time and successfully face industrial challenges.',
    'home.reggiatrici.button': 'All strapping machines',
    'home.assistance.title': 'Technical assistance and training',
    'home.assistance.rapid': 'Rapid interventions',
    'home.assistance.rapid.desc': 'We guarantee rapid assistance and scheduled maintenance interventions on all machines and products marketed.',
    'home.assistance.spare': 'Original spare parts',
    'home.assistance.spare.desc': 'We supply original spare parts to maintain optimal performance over time, even in high-intensity work environments.',
    'home.assistance.docs': 'Documentation and training',
    'home.assistance.docs.desc': 'Our technicians deliver complete technical documentation (manuals, spare parts list, certifications) and offer dedicated training to maintenance personnel, in full compliance with current regulations.',
    'home.solutions.title': 'Customized solutions for every need',
    'home.solutions.text': 'At F.lli Pozzi, you can choose from our range of manual strapping machines, and innovative and reliable solutions to meet the packaging needs of companies of every size and sector. Our experience in the sector allows us to fully understand the challenges of industrial packaging and provide personalized consultancy to guarantee the choice of products most suited to your needs.',
    'home.solutions.button': 'Packaging supplies',
    'home.cta.title': 'Choose excellence in packaging',
    'home.cta.text': 'By choosing us, you choose excellence in packaging. Contact us today to discover how we can help optimize your packaging process and improve your operational efficiency.',
    'home.cta.button': 'Contact us',
    'home.reggia.title': 'Strapping',
    'home.reggia.desc': 'Strapping in polypropylene, polyester and steel, for every industrial packaging need.',
    'home.reggia.button': 'View products',
    'home.sigilli.title': 'Seals',
    'home.sigilli.desc': 'Seals for strapping in polypropylene, polyester and steel, with different finishes.',
    'home.sigilli.button': 'View products',
    
    // Azienda
    'azienda.paragraph1': 'Fratelli Pozzi was founded in 1947 in the Bergamo area as a small craft business: since then it has recorded continuous growth both in terms of product range and production capacity, transforming a small local activity into a real company developing a commercial network spread throughout much of the world.',
    'azienda.paragraph2': 'For over 70 years, the Company, a Leader in its sector, has distinguished itself for the high quality of its products, recognized worldwide for its "Made in Italy", and for the qualified assistance it is able to provide to its customers.',
    'azienda.paragraph3': 'The company has a modern warehouse with a surface area of 2200 sqm, inside which production, assembly of strapping machines, storage of all consumable materials and technical assistance for every type of strapping machine are carried out.',
    'azienda.values.title': 'Our values',
    'azienda.values.madeInItaly': 'Made in Italy',
    'azienda.values.madeInItaly.desc': 'Italian quality recognized internationally, the result of over 75 years of experience and innovation.',
    'azienda.values.excellence': 'Excellence',
    'azienda.values.excellence.desc': 'High quality products designed to last over time and meet the most demanding market needs.',
    'azienda.values.assistance': 'Assistance',
    'azienda.values.assistance.desc': 'Qualified technical support, staff training and supply of original spare parts.',
    'azienda.cta.text': 'Contact us today to discover how we can help optimize your packaging process and improve your operational efficiency.',
    'azienda.cta.button': 'Contact us',
    
    // Contatti
    'contatti.title': 'Contact information',
    'contatti.address': 'Address:',
    'contatti.address.value': 'Via Leonardo da Vinci 37, Caravaggio 24043 (BG), Italy',
    'contatti.phone': 'Phone:',
    'contatti.email': 'E-mail:',
    'contatti.form.title': 'Send a message',
    'contatti.form.name': 'Name',
    'contatti.form.email': 'Email',
    'contatti.form.phone': 'Phone',
    'contatti.form.phone.required': 'Phone *',
    'contatti.form.message': 'Message',
    'contatti.form.submit': 'Send',
    'contatti.form.submitting': 'Sending...',
    'contatti.form.success': 'Thank you for your message! We will contact you soon.',
    'contatti.form.error.name': 'Name must contain at least 2 characters',
    'contatti.form.error.email': 'Invalid email',
    'contatti.form.error.phone': 'Phone is required',
    'contatti.form.error.message': 'Message must contain at least 10 characters',
    'contatti.form.error.submit': 'An error occurred while sending. Please try again later.',
    'contatti.cta.text': 'Contact us today for any information or quote. We are here to help you find the perfect packaging solution for your needs.',
    'contatti.cta.button': 'Contact us',
    
    // Eventi
    'eventi.title': 'Events and Trade Shows',
    'eventi.description': 'Discover the events and trade shows that Flli Pozzi participates in in the industrial packaging sector.',
    'eventi.ipack2025.title': 'IPACK-IMA 2025',
    'eventi.ipack2025.text1': 'F.lli Pozzi will be present at Ipack-Ima 2025, the main international trade fair dedicated to packaging technologies and process industry.',
    'eventi.ipack2025.text2': 'During the event we will present a preview of our new patent. An innovative solution designed to improve efficiency, ergonomics and performance.',
    'eventi.ipack2025.text3': 'The objectives are to consolidate existing commercial relationships and get in touch with new operators.',
    'eventi.ipack2025.moreInfo': 'More information by clicking on the banner.',
    'eventi.ipack2022.title': 'IPACK-IMA 2022',
    'eventi.ipack2022.text1': 'Fratelli Pozzi participated in Ipack-Ima 2022, the main appointment in processing and packaging for professionals in the food and non-food sectors, as well as an international platform for the relaunch of activities.',
    'eventi.ipack2022.text2': 'The objectives achieved are to promote the company image globally, present new products, establish and consolidate commercial relationships at an international level.',
    'eventi.ipack2022.text3': 'The main results being achieved are an increase in customers and turnover.',
    'eventi.months.gennaio': 'JANUARY',
    'eventi.months.febbraio': 'FEBRUARY',
    'eventi.months.marzo': 'MARCH',
    'eventi.months.aprile': 'APRIL',
    'eventi.months.maggio': 'MAY',
    'eventi.months.giugno': 'JUNE',
    'eventi.months.luglio': 'JULY',
    'eventi.months.agosto': 'AUGUST',
    'eventi.months.settembre': 'SEPTEMBER',
    'eventi.months.ottobre': 'OCTOBER',
    'eventi.months.novembre': 'NOVEMBER',
    'eventi.months.dicembre': 'DECEMBER',
    
    // Prodotti
    'prodotti.categories.reggiatrici': 'Strapping machines',
    'prodotti.categories.reggiatrici.desc': 'Manual, battery and pneumatic',
    'prodotti.categories.carrelli': 'Carts',
    'prodotti.categories.carrelli.desc': 'Strapping carrier',
    'prodotti.categories.reggia': 'Strapping',
    'prodotti.categories.reggia.desc': 'Polyester, polypropylene and steel',
    'prodotti.categories.sigilli': 'Seals',
    'prodotti.categories.sigilli.desc': 'Polished or galvanized',
    'prodotti.categories.accessori': 'Packaging accessories',
    'prodotti.categories.accessori.desc': 'Packaging supplies',
    'prodotti.quickNav.title': 'Quick navigation',
    'prodotti.cta.text': 'Alongside our production, we also offer a range of complementary packaging products, selected for quality and reliability. Contact us to discover all available solutions.',
    'prodotti.cta.button': 'Request information',
    'prodotti.description.plastica': 'Products in polished or galvanized steel, with smooth or embossed surface. On request with customer logo.',
    'prodotti.sections.reggiatrici.manuali': 'Manual strapping machines for polypropylene and polyester strapping',
    'prodotti.sections.reggiatrici.batteria': 'Battery strapping machines for polypropylene and polyester strapping',
    'prodotti.sections.reggiatrici.pneumaticheVibrazione': 'Pneumatic vibration strapping machines for polypropylene and polyester strapping',
    'prodotti.sections.reggiatrici.pneumaticheAcciaioConSigillo': 'Pneumatic strapping machines for steel strapping with seal for flat and round packages',
    'prodotti.sections.reggiatrici.pneumaticheAcciaioSenzaSigillo': 'Pneumatic strapping machines for steel strapping without seal for flat packages',
    'prodotti.sections.carrelli': 'Strapping trolleys',
    'prodotti.sections.reggia.title': 'Strapping',
    'prodotti.sections.reggia.polipropilene': '100% Recyclable Polypropylene Strapping',
    'prodotti.sections.reggia.poliestere': 'Polyester Strapping',
    'prodotti.sections.reggia.acciaio': 'Steel Strapping',
    'prodotti.sections.reggia.acciaio.desc': 'Single coil or wound, available polished, galvanized, blued or painted.',
    'prodotti.sections.reggia.onRequest': 'Color and customer logo available on request.',
    'prodotti.sections.sigilli.plastica': 'Seals for plastic (PP) and polyester (PET) strapping (manual tensioners)',
    'prodotti.sections.sigilli.acciaio': 'Seals for steel strapping',
    'prodotti.sections.sigilli.bulinatiLucidi': 'Polished embossed',
    'prodotti.sections.sigilli.bulinatiZincati': 'Galvanized embossed',
    'prodotti.sections.sigilli.zincati': 'Galvanized',
    'prodotti.sections.sigilli.overlap': 'Overlap',
    'prodotti.table.section': 'Section in mm',
    'prodotti.table.measure': 'Measure in mm',
    'prodotti.table.resistance': 'Resistance in kg',
    'prodotti.table.length': 'Length in meters',
    'prodotti.table.article': 'Article',
    'prodotti.table.dimensions': 'Dim. mm',
    'prodotti.table.quantity': 'Qty',
    'prodotti.table.model': 'Model',
    'prodotti.table.tensileStrength': 'Tensile strength',
    'prodotti.table.quantityFull': 'Quantity',
    'prodotti.steel.polished': 'Polished',
    'prodotti.steel.galvanized': 'Galvanized',
    'prodotti.steel.blued': 'Blued',
    'prodotti.steel.painted': 'Painted',
    'prodotti.steel.highResistance': 'High resistance',
    'prodotti.steel.upTo': 'up to',
    // Descrizioni prodotti - Reggiatrici manuali
    'prodotti.descriptions.CP2000': 'Manual strapping machine for polypropylene strapping from 9 to 19 mm with A series seal.',
    'prodotti.descriptions.BEST': 'Manual strapping machine for polypropylene strapping from 9 to 19 mm with special tensioning, for A series seal.',
    'prodotti.descriptions.PLRG': 'Manual strapping machine for polypropylene strapping from 9 to 19 mm with fast tensioning, for A series seal.',
    // Descrizioni prodotti - Reggiatrici a batteria
    'prodotti.descriptions.GTSMART': 'Battery strapping machine for PP/PET strapping 13/16 mm vibration welding for flat and round packages. Adjustable tension up to 3000 N. For strapping thicknesses up to 1.0 mm. The 14V / 3.0 AH LI-ION battery recharges in just 15 minutes.',
    'prodotti.descriptions.GTONE': 'Battery strapping machine for PP/PET strapping 13/16/19 mm vibration welding for flat and round packages. Adjustable tension up to 3000 N. For strapping thicknesses from 0.8 to 1.2. The 14V / 3.0 AH LI-ION battery recharges in just 15 minutes.',
    'prodotti.descriptions.GTXTREME': 'Battery strapping machine for PET strapping 19/25 mm vibration welding for flat and round packages. Adjustable tension up to 5000 N. For strapping thicknesses up to 1.3 mm. The 14V / 3.0 AH LI-ION battery recharges in just 15 minutes.',
    'prodotti.descriptions.CP007': 'Battery strapping machine for PP/PET strapping 13/16 mm with manual tensioning and vibration welding, flat and round packages. Adjustable tension up to 2000 N. For strapping thicknesses up to 1.0 mm. The 14V / 3.0 AH LI-ION battery recharges in just 15 minutes.',
    'prodotti.descriptions.GTMAX': 'Battery strapping machine for PET strapping 19/25 mm vibration welding for flat and round packages. Adjustable tension up to 5000 N. For strapping thicknesses up to 1.3 mm. The 14V / 3.0 AH LI-ION battery recharges in just 15 minutes.',
    'prodotti.descriptions.VIPER': 'Battery strapping machine for PET strapping 9/12/16/19 mm vibration welding for flat and round packages. The tensioning force is programmable in Newtons, Kg and pounds. Featuring an innovative touchscreen interface. 18V / 3.0 AH LI-ION battery.',
    // Descrizioni prodotti - Reggiatrici pneumatiche vibrazione
    'prodotti.descriptions.FASTPNLT': 'Pneumatic strapping machine for PP/PET strapping 13/16/19 mm vibration welding for flat and round packages adjustable tension up to 2000 N – for strapping thicknesses up to 1 mm.',
    'prodotti.descriptions.FASTPNHIGHTENSION': 'Pneumatic strapping machine for Polyester strapping 19/25/32 mm vibration welding for flat and round packages adjustable tension up to 6000 N – for strapping thicknesses up to 1.3 mm.',
    // Descrizioni prodotti - Reggiatrici pneumatiche acciaio con sigillo
    'prodotti.descriptions.FP131619': 'Pneumatic strapping machine for steel strapping from 13, 16 and 19 mm, with F series seal (Overlap). Excellent for strapping round packages. Thickness from 0.5 to 0.6 mm. Weight: 4.5 kg.',
    'prodotti.descriptions.FP19S25S32S': 'Pneumatic strapping machine for steel strapping from 19, 25 and 32 mm, with F series seal (Overlap). Weighs only 10 kg and ideal for strapping flat and round packages, thickness from 0.8 to 0.9 mm.',
    'prodotti.descriptions.FP32PLUS': 'Pneumatic strapping machine for steel strapping from 19, 25 and 32 mm, with F series seal (Overlap). Thickness from 1.0 to 1.2 mm.',
    // Descrizioni prodotti - Reggiatrici pneumatiche acciaio senza sigillo
    'prodotti.descriptions.SL3PN': 'Pneumatic strapping machine without seal for steel strapping from 13, 16 and 19 mm. Max thickness 0.6 mm. Weight: 7 kg.',
    // Descrizioni prodotti - Carrelli
    'prodotti.descriptions.GM15': 'Strapping trolley for polypropylene coils 9-19 mm, complete with box to contain strapping machines and seals. Internal diameter from 390 or 405 mm.',
    'prodotti.descriptions.FP15': 'Strapping trolley for polypropylene coils 9-19 mm, complete with box to contain strapping machines and seals. Internal diameter from 150/200/280/405 mm.',
    'prodotti.descriptions.FP93': 'Strapping trolley for polyester and steel coils from 9-32 mm and internal diameter 405 and steel with wound 13-19 mm and internal diameter 405, complete with box to contain strapping machines and seals. Internal diameter from 390 or 405 mm.',
    'prodotti.descriptions.FP15S': 'Strapping trolley for polypropylene coils with internal diameter 200-280 mm. Complete with brake and box to contain strapping machines and seals.',
    'prodotti.descriptions.FP92': 'Strapping trolley for steel coils in single coil rolls from 13 to 32 mm, complete with box to contain strapping machines and seals.',
    'prodotti.descriptions.FP13': 'Strapping trolley for textile polyester coils with int. diam. 76 mm width 140 and 150 mm.',
    
    // Footer
    'footer.tagline': 'Since 1947, leader in packaging',
    'footer.links.title': 'Links',
    'footer.info.title': 'Information',
    'footer.contacts.title': 'Contacts',
    'footer.contacts.address': 'Address: Via L. Da Vinci 37, Caravaggio (BG), Italy',
    'footer.contacts.phone': 'Phone:',
    'footer.contacts.email': 'E-mail:',
    'footer.privacy': 'Privacy Policy',
    'footer.cookies': 'Cookie Policy',
    'footer.quality': 'Quality',
    'footer.certification': 'Certification',
    'footer.copyright': 'Copyright © 2026 Flli Pozzi srl | All Rights Reserved. VAT 00215550161',
    
    // Cookies (English)
    'cookies.title': 'Cookie Policy',
    'cookies.subtitle': 'Cookie Information',
    'cookies.intro': 'Fratelli Pozzi S.r.l. provides below information regarding the operation of cookies within the site (hereinafter "Site"), also pursuant to the Privacy Authority\'s Provision "Identification of simplified methods for the information and acquisition of consent for the use of cookies" dated May 8, 2014 (hereinafter "Provision").',
    'cookies.whatAre': 'Cookies are text strings that identify the computer (through the so-called IP address) on our server, allowing information to be stored for reuse during the same, or subsequent, visit to the site. For information on why we use them, please refer to the "How we use the information collected" section of this Privacy Policy. We do not use the IP address as a means to identify the user.',
    'cookies.storage': 'Cookies are stored according to the User\'s preferences, by the individual browser, on the specific device. Generally, there is the possibility to set the computer so that: accept all cookies, be informed when a cookie is issued or not receive cookies.',
    'cookies.browserSettings': 'With most browsers, this function can be reached through the "tools" menu (e.g. Internet Explorer), "edit" or "task" (e.g. Netscape). If you have difficulty finding this area, the "help" function within the browser will be able to provide assistance. You can also find more detailed information about cookies and how to manage them at',
    'cookies.necessary': 'These cookies are strictly necessary to provide you with the services available through our Website and to use some of its features.',
    'cookies.disabling': 'It is important to note that by disabling all Cookies, the functioning of this site may be compromised.',
    'cookies.thirdParty': 'In case of services provided by third parties, the User can also exercise their right to object to tracking by informing themselves through the third party\'s privacy policy, through the opt-out link, if explicitly provided, or by contacting them directly.',
    'cookies.howUse': 'How do we use cookies?',
    'cookies.howUse.text1': 'Based on function and purpose of use, cookies can be classified into technical cookies, analytical cookies, profiling cookies. All cookies are distinguished into first-party cookies, installed directly by the Site manager and third-party cookies, installed through the Site by third parties.',
    'cookies.howUse.text2': 'Based on the characteristics and use of cookies we can distinguish different categories:',
    'cookies.navigation.title': 'Navigation Cookies',
    'cookies.navigation.text1': 'Through Navigation Cookies, the Site tracks the cookie path (so-called "click stream" activity, i.e., recording of paths followed by site visitors when moving from one page to another) without this activity being able to know or identify the user who entered the site, in order to collect statistical data on the site such as, for example, pages visited, pages downloaded, etc.',
    'cookies.navigation.text2': 'We reiterate that none of this information is associated with you individually. Cookies do not capture your personal email address, nor any of your private information. Information derived from cookie tracking is evaluated only in aggregate. Web server log files are also used to count visitors and evaluate the technical capabilities of our site. We use all this information to know how many people visit the Site, to organize pages in the most accessible way possible, to facilitate navigation on the site and to make its pages more useful for users. We collect information about site traffic, but not about individual visitors. Consequently, no information that specifically concerns you can be stored or used.',
    'cookies.session.title': 'Session Cookies',
    'cookies.session.text1': 'Session Cookies are strictly necessary to provide you with the services available through our Website and to use some of its features.',
    'cookies.session.text2': 'Since these cookies are strictly necessary to provide the Website, it is not possible to refuse them without affecting the functioning of our site, but it is still possible to block or delete them by modifying the browser settings and impose the blocking of all cookies on this Website.',
    'cookies.analytics.title': 'Google Analytics Cookies',
    'cookies.analytics.text1': 'Google Analytics Cookies collect information that is used in aggregate form to help us understand how our website is used or the effectiveness of our marketing campaigns or to help us customize the site to improve your experience.',
    'cookies.analytics.text2': 'This website uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses "cookies" which are text files placed on your computer to enable the website to analyze how users use the site. The information generated by the cookie about your use of the website (including your anonymous IP address) will be transmitted to and stored by Google servers in the United States.',
    'cookies.analytics.text3': 'Google will use this information for the purpose of examining your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google\'s behalf. Google will not associate your IP address with any other data held by Google.',
    'cookies.analytics.text4': 'You may refuse the use of cookies by selecting the appropriate settings on your browser, but please note that if you do this you may not be able to use all the features of this website.',
    'cookies.analytics.text5': 'You can prevent Google from detecting a cookie that is generated due to and linked to your use of this website (including your IP address) and the processing of such data by downloading and installing this browser plugin:',
    'cookies.analytics.text6': 'The privacy policy used by Google for the Analytics functionality can be consulted at this link:',
    'cookies.profiling.title': 'Profiling Cookies',
    'cookies.profiling.text1': 'Profiling Cookies create profiles related to the user and are used to send advertising messages in line with the preferences expressed by the same in the context of web browsing.',
    'cookies.profiling.text2': 'The data controller has decided not to use them due to the particular invasiveness that such devices can have in the private sphere of users.',
    'cookies.sharing.text1': 'Cookies collected for the purposes listed above may be communicated to the competent subjects in charge of site management for the performance, even partial, of activities related to the assignment.',
    'cookies.sharing.text2': 'This Site exclusively uses technical, navigation or session and analytics cookies, to allow navigation and provide the service requested by the User.',
    'cookies.sharing.text3': 'For all cookies other than technical ones, the User\'s express consent is required the first time they visit the Site. Consent is tracked on subsequent visits, however the User always has the possibility to revoke in whole or in part the consent already given.',
    'cookies.duration.title': 'Duration',
    'cookies.duration.text1': 'Some cookies (session cookies) remain active only until the browser is closed. Other cookies (persistent cookies) "survive" the browser closing and are also available on subsequent visits by the user, and their duration is set by the server at the time of their creation with a predetermined expiration date.',
    'cookies.duration.text2': 'The setting can be defined specifically for different websites and web applications. Furthermore, the most common browsers allow you to define different settings for various types of cookies.',
    'cookies.duration.text3': 'You can set the browser to be notified in case of cookie insertion attempts, limit them or completely refuse them.',
    'cookies.changes.title': 'Changes to this information',
    'cookies.changes.text': 'This Information is in force from May 25, 2018. Fratelli Pozzi S.r.l. reserves the right to modify its content, in part or completely, also due to changes in Privacy Regulations. Fratelli Pozzi S.r.l. will publish the updated version of this document on the Site, and from that moment it will be binding: therefore you are invited to visit this section regularly.',
    'cookies.dataController': 'Data controller:',
    'cookies.dataController.value': 'Fratelli Pozzi S.r.l. with registered office at via Leonardo Da Vinci, 37 Caravaggio, 24043 BG – VAT 00215550161.',
    'cookies.moreInfo': 'Given the objective complexity related to the identification of Cookie-based technologies and their very close integration with the functioning of the web, please refer to the following link',
    
    // Privacy (English)
    'privacy.title': 'Privacy Policy',
    'privacy.subtitle': 'Personal data management',
    'privacy.intro1': 'Fratelli Pozzi S.r.l. pursuant to Legislative Decree 30 June 2003, n. 196 - Privacy Code (hereinafter "Code") modified and updated by Legislative Decree 101/2018, articles 4, n. 7), 13, 14 and 24 of EU Regulation no. 679 of 27 April 2016 relating to the protection of natural persons with regard to the processing of personal data, as well as the free circulation of such data (hereinafter, "Regulation" or "GDPR"), informs you that in carrying out its activity it pays maximum attention to the security and confidentiality of the personal data of its users.',
    'privacy.intro2': 'The Company is therefore the data controller of the personal data collected on this website. The Regulation was born with the intent to harmonize the legislation of the European Union, guaranteeing greater control over how personal data is processed. Following its entry into force, which took place on May 25, 2018, the Company has undertaken a path of adaptation of processes and internal policies in the protection of all information that our Company will come into possession of. This statement describes what types of information we collect, how it is used, what we share with other organizations, how rights regarding information in our possession can be exercised and how to contact our company.',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.products': 'Produits',
    'nav.company': 'L\'Entreprise',
    'nav.events': 'Événements',
    'nav.contacts': 'Contacts',
    
    // Home
    'home.hero.title': 'Flli Pozzi srl',
    'home.hero.subtitle': 'Depuis 1947, leader dans l\'emballage',
    'home.features.madeInItaly': 'Made in Italy',
    'home.features.madeInItaly.desc': 'Qualité italienne reconnue dans le monde entier',
    'home.features.excellence': 'Excellence',
    'home.features.excellence.desc': 'Produits de haute qualité pour tous les besoins',
    'home.features.assistance': 'Assistance',
    'home.features.assistance.desc': 'Support technique qualifié et formation',
    'home.reggiatrici.title': 'Cerceleuses depuis 1947',
    'home.reggiatrici.text': 'Nous produisons des cerceleuses et tendeurs manuels Made in Italy, synonymes de qualité, résistance et fiabilité. Adaptés à diverses applications industrielles, chaque appareil a été conçu pour donner le meilleur sous tous les efforts. Avec nous, vous obtiendrez non seulement des tendeurs de qualité supérieure, mais aussi la certitude d\'investir dans des solutions d\'emballage conçues pour durer dans le temps et relever les défis industriels avec succès.',
    'home.reggiatrici.button': 'Toutes les cerceleuses',
    'home.assistance.title': 'Assistance technique et formation',
    'home.assistance.rapid': 'Interventions rapides',
    'home.assistance.rapid.desc': 'Nous garantissons des interventions rapides d\'assistance et de maintenance programmée sur toutes les machines et produits commercialisés.',
    'home.assistance.spare': 'Pièces de rechange d\'origine',
    'home.assistance.spare.desc': 'Nous fournissons des pièces de rechange d\'origine pour maintenir des performances optimales dans le temps, même dans des environnements de travail à haute intensité.',
    'home.assistance.docs': 'Documentation et formation',
    'home.assistance.docs.desc': 'Nos techniciens livrent la documentation technique complète (manuels, liste des pièces de rechange, certifications) et offrent une formation dédiée au personnel de maintenance, dans le plein respect des normes en vigueur.',
    'home.solutions.title': 'Solutions personnalisées pour chaque besoin',
    'home.solutions.text': 'Nous proposons des solutions d\'emballage sur mesure adaptées aux besoins spécifiques de chaque client. Notre équipe d\'experts travaille en étroite collaboration avec vous pour développer des solutions qui optimisent vos processus d\'emballage.',
    'home.solutions.button': 'Découvrez nos solutions',
    'home.reggia.title': 'Cerceaux',
    'home.reggia.desc': 'Cerceaux en polypropylène, polyester et acier, pour tous les besoins d\'emballage industriel.',
    'home.reggia.button': 'Voir les produits',
    'home.sigilli.title': 'Sceaux',
    'home.sigilli.desc': 'Sceaux pour cerceaux en polypropylène, polyester et acier, avec différentes finitions.',
    'home.sigilli.button': 'Voir les produits',
    'home.cta.title': 'Choisissez l\'excellence dans l\'emballage',
    'home.cta.text': 'En nous choisissant, vous choisissez l\'excellence dans l\'emballage. Contactez-nous aujourd\'hui pour découvrir comment nous pouvons contribuer à optimiser votre processus d\'emballage et améliorer votre efficacité opérationnelle.',
    'home.cta.button': 'Contactez-nous',
    
    // Azienda
    'azienda.title': 'L\'Entreprise',
    'azienda.text1': 'Fratelli Pozzi S.r.l. est une entreprise italienne leader dans le secteur de l\'emballage industriel depuis 1947. Avec plus de 75 ans d\'expérience, nous nous sommes spécialisés dans la production de cerceleuses, tendeurs, cerceaux et sceaux pour l\'emballage industriel.',
    'azienda.values.title': 'Nos Valeurs',
    'azienda.values.madeInItaly': 'Made in Italy',
    'azienda.values.madeInItaly.desc': 'Qualité et excellence italiennes reconnues dans le monde entier',
    'azienda.values.innovation': 'Innovation',
    'azienda.values.innovation.desc': 'Recherche constante de nouvelles solutions et technologies',
    'azienda.values.service': 'Service',
    'azienda.values.service.desc': 'Assistance technique et support client de qualité',
    'azienda.cta.text': 'Découvrez comment nous pouvons vous aider à optimiser vos processus d\'emballage. Contactez-nous pour plus d\'informations.',
    'azienda.cta.button': 'Contactez-nous',
    
    // Contatti
    'contatti.title': 'Contactez-nous',
    'contatti.address': 'Adresse',
    'contatti.address.value': 'Via Leonardo da Vinci 37, 24043 Caravaggio (BG), Italie',
    'contatti.phone': 'Téléphone',
    'contatti.email': 'Email',
    'contatti.form.title': 'Envoyez-nous un message',
    'contatti.form.name': 'Nom',
    'contatti.form.email': 'Email',
    'contatti.form.phone.required': 'Téléphone *',
    'contatti.form.message': 'Message',
    'contatti.form.submit': 'Envoyer',
    'contatti.form.submitting': 'Envoi en cours...',
    'contatti.form.success': 'Merci pour votre message ! Nous vous contacterons bientôt.',
    'contatti.form.error.name': 'Le nom doit contenir au moins 2 caractères',
    'contatti.form.error.email': 'Email invalide',
    'contatti.form.error.phone': 'Le téléphone est obligatoire',
    'contatti.form.error.message': 'Le message doit contenir au moins 10 caractères',
    'contatti.form.error.submit': 'Une erreur s\'est produite lors de l\'envoi. Veuillez réessayer plus tard.',
    'contatti.cta.text': 'Contactez-nous aujourd\'hui pour toute information ou devis. Nous sommes là pour vous aider à trouver la solution d\'emballage parfaite pour vos besoins.',
    'contatti.cta.button': 'Contactez-nous',
    
    // Eventi
    'eventi.title': 'Événements et Salons',
    'eventi.description': 'Découvrez les événements et salons auxquels Flli Pozzi participe dans le secteur de l\'emballage industriel.',
    'eventi.ipack2025.title': 'IPACK-IMA 2025',
    'eventi.ipack2025.text1': 'F.lli Pozzi sera présent à Ipack-Ima 2025, le principal salon international dédié aux technologies de l\'emballage et de l\'industrie de transformation.',
    'eventi.ipack2025.text2': 'Lors de l\'événement, nous présenterons en avant-première notre nouveau brevet. Une solution innovante conçue pour améliorer l\'efficacité, l\'ergonomie et les performances.',
    'eventi.ipack2025.text3': 'Les objectifs sont de consolider les relations commerciales existantes et d\'entrer en contact avec de nouveaux opérateurs.',
    'eventi.ipack2025.moreInfo': 'Plus d\'informations en cliquant sur la bannière.',
    'eventi.ipack2022.title': 'IPACK-IMA 2022',
    'eventi.ipack2022.text1': 'Fratelli Pozzi a participé à Ipack-Ima 2022, rendez-vous principal dans le traitement et l\'emballage pour les professionnels des secteurs alimentaire et non alimentaire, ainsi que plateforme internationale pour la relance des activités.',
    'eventi.ipack2022.text2': 'Les objectifs atteints sont de promouvoir l\'image de l\'entreprise au niveau mondial, présenter les nouveaux produits, établir et consolider les relations commerciales au niveau international.',
    'eventi.ipack2022.text3': 'Les principaux résultats en cours d\'atteinte sont l\'augmentation de la clientèle et du chiffre d\'affaires.',
    'eventi.months.gennaio': 'JANVIER',
    'eventi.months.febbraio': 'FÉVRIER',
    'eventi.months.marzo': 'MARS',
    'eventi.months.aprile': 'AVRIL',
    'eventi.months.maggio': 'MAI',
    'eventi.months.giugno': 'JUIN',
    'eventi.months.luglio': 'JUILLET',
    'eventi.months.agosto': 'AOÛT',
    'eventi.months.settembre': 'SEPTEMBRE',
    'eventi.months.ottobre': 'OCTOBRE',
    'eventi.months.novembre': 'NOVEMBRE',
    'eventi.months.dicembre': 'DÉCEMBRE',
    
    // Prodotti
    'prodotti.categories.reggiatrici': 'Cerceleuses et tendeurs',
    'prodotti.categories.reggiatrici.desc': 'Manuels, à batterie et pneumatiques',
    'prodotti.categories.carrelli': 'Chariots',
    'prodotti.categories.carrelli.desc': 'Porte-cerceaux',
    'prodotti.categories.reggia': 'Cerceaux',
    'prodotti.categories.reggia.desc': 'Polyester, polypropylène et acier',
    'prodotti.categories.sigilli': 'Sceaux',
    'prodotti.categories.sigilli.desc': 'Polis ou galvanisés',
    'prodotti.categories.accessori': 'Accessoires pour l\'emballage',
    'prodotti.categories.accessori.desc': 'Fournitures pour l\'emballage',
    'prodotti.quickNav.title': 'Navigation rapide',
    'prodotti.cta.text': 'En plus de notre production, nous offrons également une gamme de produits complémentaires pour l\'emballage, sélectionnés pour leur qualité et leur fiabilité. Contactez-nous pour découvrir toutes les solutions disponibles.',
    'prodotti.cta.button': 'Demander des informations',
    'prodotti.table.section': 'Section en mm',
    'prodotti.table.measure': 'Mesure en mm',
    'prodotti.table.resistance': 'Résistance en kg',
    'prodotti.table.length': 'Longueur en mètres',
    'prodotti.table.article': 'Article',
    'prodotti.table.dimensions': 'Dim. mm',
    'prodotti.table.quantity': 'Qté',
    'prodotti.table.model': 'Modèle',
    'prodotti.table.tensileStrength': 'Résistance à la traction',
    'prodotti.table.quantityFull': 'Quantité',
    'prodotti.steel.polished': 'Poli',
    'prodotti.steel.galvanized': 'Galvanisé',
    'prodotti.steel.blued': 'Bleui',
    'prodotti.steel.painted': 'Peint',
    'prodotti.steel.highResistance': 'Haute résistance',
    'prodotti.steel.upTo': 'jusqu\'à',
    
    // Footer
    'footer.tagline': 'Leader dans l\'emballage depuis 1947',
    'footer.links.title': 'Liens',
    'footer.info.title': 'Informations',
    'footer.contacts.title': 'Contacts',
    'footer.quality': 'Qualité',
    'footer.certification': 'Certification',
    'footer.copyright': '© 2024 Flli Pozzi srl. Tous droits réservés.',
    
    // Cookies e Privacy (traduzioni principali)
    'cookies.title': 'Politique des Cookies',
    'cookies.subtitle': 'Gestion des cookies',
    'privacy.title': 'Politique de Confidentialité',
    'privacy.subtitle': 'Gestion des données personnelles',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('it');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'it' || savedLanguage === 'en' || savedLanguage === 'fr')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
